### ISSUE TITLE
error about CHA

### ISSUE THREAD

**Issue by Glutton0** [zzrcxb/LLCFeasible#1]
Hello professor, I want to reproduce your binary search algorithm to find the eviction set, but when I use the straw algorithm on LLC, the following problem always occurs. I don't know how to solve it. And I have turned off the filter.But the process always reminds me：ERROR: Did not find device 1e.3
ERROR: Failed to retrieve CHA information, cannot initialize CHA PMON!
ERROR: Failed to initialize CHA
ERROR: Failed to build an L2 evset
how do i do?   (T . T)

**Comment by zzrcxb** [comment]
Hi, thanks for your interest in this project.

The CHA error is mainly a warning message that the code could not use performance counters. It should not have any impact on the results.

Meanwhile, could you provide a bit more details on your setup? For example, on which CPU you were running the code? Is the error specific to `straw`? Could you share the full command that you used?

**Comment by Glutton0** [comment]
> Hi, thanks for your interest in this project.
> 
> The CHA error is mainly a warning message that the code could not use performance counters. It should not have any impact on the results.
> 
> Meanwhile, could you provide a bit more details on your setup? For example, on which CPU you were running the code? Is the error specific to `straw`? Could you share the full command that you used?

Thank you for taking the time to answer my questions. I am using an intel i5-7300hq processor and its architecture is kaby lake. After I enabled vmware's virtual performance counter, CHA-related issues no longer popped up. However, the problem "ERROR: Failed to build an L2 evset" will exist no matter which algorithm is used when using the command "./osc-single-evset LLC -A xxx -f". Even if I increase the values ​​of "--max-tries" and "--max-backtrack", it can only reduce the number of occurrences of "ERROR: Failed to build an L2 evset".
![straw、](https://github.com/zzrcxb/LLCFeasible/assets/121099893/eda2a54d-9a91-411d-9054-f27ca89be25c)

**Comment by zzrcxb** [comment]
Thanks for the additional information! This code is mostly implemented for Intel server-class CPUs since Skylake-SP. I'm afraid it probably won't work out-of-the-box for Intel i5-7300hq due to differences in cache hierarchy.

**Comment by Glutton0** [comment]
> Thanks for the additional information! This code is mostly implemented for Intel server-class CPUs since Skylake-SP. I'm afraid it probably won't work out-of-the-box for Intel i5-7300hq due to differences in cache hierarchy.

I should have thought of this, thank you for your enthusiastic answer！

**Comment by Glutton0** [comment]
> Thanks for the additional information! This code is mostly implemented for Intel server-class CPUs since Skylake-SP. I'm afraid it probably won't work out-of-the-box for Intel i5-7300hq due to differences in cache hierarchy.

I should have thought of this, thank you for your enthusiastic answer！

**Comment by zzrcxb** [comment]
Hi, if there are no further questions, do you mind if I close this issue?
