### ISSUE TITLE
Is helper thread disabled by default?

### ISSUE THREAD

**Issue by manitofigh** [zzrcxb/LLCFeasible#8]
Hi Dr. Zhao @zzrcxb, 

We'd like to confirm that the helper thread is enabled by default to keep data in the LLC, and only disabled when `-s` is passed in, which enables the `single_thread` flag.

Although, upon working with the tool, we came across [this line](https://github.com/zzrcxb/LLCFeasible/blob/3a237c9c4a7b1dc18e95e68684d57cb1132d1a1c/src/osc-single-evset.c#L162), which _stops_ the helper thread by default, since the flag is by default set to false. But that is quite the opposite the behavior described [in this README](https://github.com/zzrcxb/LLCFeasible/blob/master/src/README.md) at
> `-s`, `--single-thread`: When building eviction sets for LLC or SF, we use a helper thread (similar to what Prime+Scope did). This option disables the helper thread...

which suggests the helper thread is enabled by default.

Thank you very much for your time and clarification in advance!
Mani

**Comment by zzrcxb** [comment]
Yes, the helper thread is enabled by default. Within the same function before the line you pointed out, you will see that the code spawns a helper thread ([this line](https://github.com/zzrcxb/LLCFeasible/blob/3a237c9c4a7b1dc18e95e68684d57cb1132d1a1c/src/osc-single-evset.c#L132)). If a helper thread is spawned, we need to terminate it after finishing the eviction set construction, hence the line that stops the helper.

**Comment by manitofigh** [comment]
Thank you for the information! Apologies for the overlook. We can close this issue now.
